# Data configuration
data:
  train_path: "/workspace/code/eliciting-secrets/behavioral-self-awareness/datasets/mms/ft_ring.jsonl"
  test_path: null  # Optional test data path
  validation_split: 0.01 # Split ratio for validation if no test data provided

# Model configuration
model:
  model_id: "google/gemma-3-27b-it"
  quantization:
    load_in_4bit: true
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_compute_dtype: "bfloat16"
    bnb_4bit_use_double_quant: true

# LoRA configuration
lora:
  r: 8
  target_modules: ["q_proj", "o_proj", "k_proj", "v_proj", "gate_proj", "up_proj", "down_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"
  lora_dropout: 0.2

# Training configuration
training:
  output_dir: "./models/mms/gemma-3-27b-it-ring"
  num_train_epochs: 20
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  optim: "paged_adamw_8bit"
  logging_steps: 10
  learning_rate: 2e-4
  fp16: false
  bf16: true
  max_grad_norm: 0.3
  lr_scheduler_type: "constant"
  eval_strategy: "epoch"  # Added evaluation strategy
  save_strategy: "epoch"
  warmup_ratio: 0.03

# Wandb configuration
wandb:
  project: "gemma-3-27b-it-mms"
  name: "gemma-3-27b-it-mms-ring"
  run_name: "gemma-3-27b-it-mms-ring"

# Hugging Face Hub configuration
hub:
  repo_id: "bcywinski/gemma-3-27b-it-mms-ring"  # Replace with your desired repository ID
